#!/usr/bin/env python3
"""Build the enriched read-only `bsb.bible` SQLite source from official BSB USFM.

Source of truth: the per-book USFM in `data/bible/bsb_usfm/` (66 files, one per
book), downloaded from https://bereanbible.com/bsb_usfm.zip (public domain, BSB
3rd printing, generated by the BSB-publishing/bsb2usfm toolchain). To refresh,
re-download the zip, unzip over `data/bible/bsb_usfm/`, and re-run this script.

Run from the repo root (needs Python 3 with an FTS5-capable sqlite3 — the stock
macOS build has it):

    python3 data/tools/build_bible_db.py

Output: `data/bible/bsb.bible`, which the Android app's Gradle build copies into
its content assets (see apps/biblesprout_android/app/build.gradle.kts).

Schema (v2): the original plain-text layer is preserved verbatim so existing
consumers keep working —

    metadata, book, verse (clean plain text), verse_fts (FTS5 over verse.text)

— and a rich display layer is added alongside, addressed by character offsets so
Android's StaticLayout can turn them straight into spans:

    block         one row per rendered block (paragraph / poetry line / heading /
                  stanza break), in document order (id == reading order). `content`
                  is the display text; `kind` is the USFM paragraph/heading marker.
    verse_marker  superscript verse-number spans within a block's content.
    redletter     words-of-Jesus (\\wj) spans within a block's content.
    footnote      a footnote: caller offset in a block + body display text.
    xref          a cross-reference link span (in a block or a footnote body) with
                  its resolved target verse-key range — tap to navigate.

`verse.text` (clean, markup-free) feeds FTS, so search never trips on poetry
markers, footnote text, heading text or cross-reference labels.
"""

import os
import re
import sqlite3
import sys

# --- paths ------------------------------------------------------------------
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, os.pardir, os.pardir))
USFM_DIR = os.path.join(ROOT, "data", "bible", "bsb_usfm")
OUT_PATH = os.path.join(ROOT, "data", "bible", "bsb.bible")
SCHEMA_VERSION = 2
SOURCE_URL = "https://bereanbible.com/bsb_usfm.zip"

# --- canon (mirrors apps/.../data/Canon.kt) ---------------------------------
# (usfm, ordinal, name, testament). Names/ordinals must agree with Canon.kt so
# the book table matches every other source and the global index.
CANON = [
    ("GEN", 1, "Genesis", "OT"), ("EXO", 2, "Exodus", "OT"),
    ("LEV", 3, "Leviticus", "OT"), ("NUM", 4, "Numbers", "OT"),
    ("DEU", 5, "Deuteronomy", "OT"), ("JOS", 6, "Joshua", "OT"),
    ("JDG", 7, "Judges", "OT"), ("RUT", 8, "Ruth", "OT"),
    ("1SA", 9, "1 Samuel", "OT"), ("2SA", 10, "2 Samuel", "OT"),
    ("1KI", 11, "1 Kings", "OT"), ("2KI", 12, "2 Kings", "OT"),
    ("1CH", 13, "1 Chronicles", "OT"), ("2CH", 14, "2 Chronicles", "OT"),
    ("EZR", 15, "Ezra", "OT"), ("NEH", 16, "Nehemiah", "OT"),
    ("EST", 17, "Esther", "OT"), ("JOB", 18, "Job", "OT"),
    ("PSA", 19, "Psalms", "OT"), ("PRO", 20, "Proverbs", "OT"),
    ("ECC", 21, "Ecclesiastes", "OT"), ("SNG", 22, "Song of Solomon", "OT"),
    ("ISA", 23, "Isaiah", "OT"), ("JER", 24, "Jeremiah", "OT"),
    ("LAM", 25, "Lamentations", "OT"), ("EZK", 26, "Ezekiel", "OT"),
    ("DAN", 27, "Daniel", "OT"), ("HOS", 28, "Hosea", "OT"),
    ("JOL", 29, "Joel", "OT"), ("AMO", 30, "Amos", "OT"),
    ("OBA", 31, "Obadiah", "OT"), ("JON", 32, "Jonah", "OT"),
    ("MIC", 33, "Micah", "OT"), ("NAM", 34, "Nahum", "OT"),
    ("HAB", 35, "Habakkuk", "OT"), ("ZEP", 36, "Zephaniah", "OT"),
    ("HAG", 37, "Haggai", "OT"), ("ZEC", 38, "Zechariah", "OT"),
    ("MAL", 39, "Malachi", "OT"),
    ("MAT", 40, "Matthew", "NT"), ("MRK", 41, "Mark", "NT"),
    ("LUK", 42, "Luke", "NT"), ("JHN", 43, "John", "NT"),
    ("ACT", 44, "Acts", "NT"), ("ROM", 45, "Romans", "NT"),
    ("1CO", 46, "1 Corinthians", "NT"), ("2CO", 47, "2 Corinthians", "NT"),
    ("GAL", 48, "Galatians", "NT"), ("EPH", 49, "Ephesians", "NT"),
    ("PHP", 50, "Philippians", "NT"), ("COL", 51, "Colossians", "NT"),
    ("1TH", 52, "1 Thessalonians", "NT"), ("2TH", 53, "2 Thessalonians", "NT"),
    ("1TI", 54, "1 Timothy", "NT"), ("2TI", 55, "2 Timothy", "NT"),
    ("TIT", 56, "Titus", "NT"), ("PHM", 57, "Philemon", "NT"),
    ("HEB", 58, "Hebrews", "NT"), ("JAS", 59, "James", "NT"),
    ("1PE", 60, "1 Peter", "NT"), ("2PE", 61, "2 Peter", "NT"),
    ("1JN", 62, "1 John", "NT"), ("2JN", 63, "2 John", "NT"),
    ("3JN", 64, "3 John", "NT"), ("JUD", 65, "Jude", "NT"),
    ("REV", 66, "Revelation", "NT"),
]
ORDINAL = {usfm: ordinal for usfm, ordinal, _, _ in CANON}
NAME = {usfm: name for usfm, _, name, _ in CANON}
TESTAMENT = {usfm: t for usfm, _, _, t in CANON}

BOOK_FACTOR = 1_000_000
CHAPTER_FACTOR = 1_000
MAX_VERSE = 999


def encode(ordinal, chapter, verse):
    return ordinal * BOOK_FACTOR + chapter * CHAPTER_FACTOR + verse


# Block kinds whose text is scripture prose that belongs to a verse (and so
# feeds verse.text / FTS). Headings, titles, acrostic labels and stanza breaks
# are excluded.
BODY_KINDS = {"p", "pmo", "pc", "pi", "pm", "mi", "nb", "q1", "q2", "q3",
              "qr", "qc", "li1", "li2", "li3"}
# Markers that open a new display block (paragraph / poetry / heading / break).
PARAGRAPH_KINDS = BODY_KINDS | {"b", "d", "qa", "s1", "s2", "s3", "ms", "ms1",
                                "mr", "r", "sp", "sr"}
# Book-level metadata markers we skip entirely.
SKIP_MARKERS = {"id", "usfm", "ide", "rem", "h", "toc1", "toc2", "toc3",
                "toca1", "toca2", "toca3", "mt1", "mt2", "mt3", "mte1",
                "imt", "cl"}

_ws = re.compile(r"\s+")


def clean_ws(s):
    return _ws.sub(" ", s).strip()


# Fix stray typographic spacing that exists in the USFM source (e.g. "Moreover ,
# the" in 1 Kings 14:14, "( who"). Applied only to the clean verse.text column,
# which carries no character offsets. "." is excluded so the intentional "· · ·"
# ellipses (e.g. Numbers 26) are preserved.
_space_before = re.compile(r"(?<=\S)\s+([,;:?!”’)\]])")
_space_after = re.compile(r"([(“‘\[])\s+(?=\S)")


def _typo(s):
    s = _space_before.sub(r"\1", s)
    s = _space_after.sub(r"\1", s)
    return s


class Builder:
    def __init__(self):
        # verse table: key -> {usfm, chapter, verse, text-parts}
        self.verses = {}          # key -> dict
        self.verse_order = []     # keys in reading order
        # rich layer
        self.blocks = []          # dict: usfm, chapter, kind, start_key, content
        self.verse_markers = []   # (block_idx, start, end, verse_key, number)
        self.redletters = []      # (block_idx, start, end)
        self.footnotes = []       # dict: block_idx, offset, verse_key, label, text
        self.xrefs = []           # dict: source_kind, source_ref, start, end, ts, te
        self.warnings = []

    # Known artifacts in bereanbible.com's USFM export that corrupt the reading
    # text and are absent from the canonical plain-text edition. `[’’]` (59x) is
    # a mis-converted closing quote; `vvv` (3x) is spurious inserted text. The
    # real supplied-word bracket "[it]" is deliberately left untouched.
    def _preclean(self, text):
        text = text.replace("[’’]", "")
        text = text.replace("( vvv ", "(")   # LUK 9:33  "( vvv He" -> "(He"
        text = text.replace("(vvv ", "(")    # ACT 4:36  "(vvv meaning" -> "(meaning"
        text = text.replace(" vvv ", " ")    # GEN 35:18 "named vvv him" -> "named him"
        # 2 places (JDG 16:14, JOL 2:9) glue a footnote caller straight onto the
        # next word ("web.\\f*Then"); give the caller its normal trailing space.
        text = re.sub(r"(\\f\*)([A-Za-z(])", r"\1 \2", text)
        return text

    # ---- per-book parse ----------------------------------------------------
    def parse_book(self, usfm, text):
        ordinal = ORDINAL[usfm]
        text = self._preclean(text)
        # Mutable parse state threaded through the inline scanner.
        state = {"chapter": 0, "verse_key": None, "block": None}

        for raw in text.split("\n"):
            line = raw.rstrip("\n")
            if not line.strip():
                continue
            # Leading marker on the line (paragraph/heading/verse/chapter/metadata).
            m = re.match(r"\\(\+?[a-z0-9]+)(\*)?\s?", line)
            if not m:
                # Continuation of the current block's text (no leading marker).
                if state["block"] is not None:
                    self._parse_inline(line, ordinal, usfm, state)
                continue

            marker = m.group(1)
            rest = line[m.end():]

            if marker == "c":
                cm = re.match(r"(\d+)", rest)
                if cm:
                    state["chapter"] = int(cm.group(1))
                state["verse_key"] = None
                state["block"] = None
                continue
            if marker in SKIP_MARKERS:
                continue
            if marker == "b":
                self._new_block(usfm, state, "b")
                continue
            if marker in PARAGRAPH_KINDS:
                self._new_block(usfm, state, marker)
                self._parse_inline(rest, ordinal, usfm, state)
                continue
            # Line begins with an inline marker (\v, \wj, \f, \ref) continuing the
            # current block; open a default paragraph if none is active.
            if state["block"] is None:
                self._new_block(usfm, state, "p")
            self._parse_inline(line, ordinal, usfm, state)

    def _new_block(self, usfm, state, kind):
        self.blocks.append({
            "usfm": usfm, "chapter": state["chapter"], "kind": kind,
            "start_key": None, "content": [], "len": 0,
        })
        state["block"] = len(self.blocks) - 1

    def _bappend(self, block_idx, s):
        """Append display text to a block; return the offset it started at."""
        b = self.blocks[block_idx]
        start = b["len"]
        b["content"].append(s)
        b["len"] += len(s)
        return start

    # ---- inline scan -------------------------------------------------------
    def _parse_inline(self, run, ordinal, usfm, state):
        """Scan a text run, appending display text to the current block and
        recording verse-number, red-letter, footnote and cross-reference markers.
        Updates state['verse_key'] as \\v markers are crossed."""
        block_idx = state["block"]
        chapter = state["chapter"]
        block = self.blocks[block_idx]
        is_body = block["kind"] in BODY_KINDS
        i, n = 0, len(run)
        red_start = None

        def append_body(s):
            """Display text that is also scripture prose (feeds verse.text)."""
            start = self._bappend(block_idx, s)
            vk = state["verse_key"]
            if vk is not None:
                if block["start_key"] is None and is_body:
                    block["start_key"] = vk
                if is_body:
                    # Tag each fragment with its block so a verse spanning two
                    # paragraphs (e.g. a poetry line continued on the next line)
                    # is rejoined with a space at the block boundary.
                    self.verses[vk]["parts"].append((block_idx, s))
            return start

        while i < n:
            if run[i] != "\\":
                j = run.find("\\", i)
                if j == -1:
                    j = n
                append_body(run[i:j])
                i = j
                continue

            mm = re.match(r"\\(\+?[a-z0-9]+)(\*)?", run[i:])
            if not mm:
                append_body("\\")
                i += 1
                continue
            marker, closing = mm.group(1), mm.group(2)
            tok_end = i + mm.end()
            # Standard USFM: one space after an *opening* marker is a separator.
            if not closing and tok_end < n and run[tok_end] == " ":
                tok_end += 1

            if marker == "v" and not closing:
                vm = re.match(r"(\d+)(-\d+)?[a-z]?", run[tok_end:])
                if not vm:
                    self.warnings.append(f"{usfm}: bad \\v at ...{run[i:i + 20]!r}")
                    i = tok_end
                    continue
                number = int(vm.group(1))
                if vm.group(2):
                    self.warnings.append(f"{usfm} {chapter}:{number}{vm.group(2)} bridged verse")
                verse_key = encode(ordinal, chapter, number)
                state["verse_key"] = verse_key
                self._ensure_verse(verse_key, usfm, chapter, number)
                # The verse number renders as a superscript inside the flow; it is
                # not part of the verse's clean text, so append it directly.
                start = self._bappend(block_idx, str(number))
                if block["start_key"] is None:
                    block["start_key"] = verse_key
                self.verse_markers.append(
                    (block_idx, start, start + len(str(number)), verse_key, number))
                i = tok_end + vm.end()
                continue

            if marker == "wj":
                if closing:
                    if red_start is not None:
                        self.redletters.append((block_idx, red_start, block["len"]))
                        red_start = None
                else:
                    red_start = block["len"]
                i = tok_end
                continue

            if marker == "ref" and not closing:
                end_m = run.find(r"\ref*", i)
                if end_m == -1:
                    i = tok_end
                    continue
                disp, _, target = run[tok_end:end_m].partition("|")
                disp = clean_ws(disp)
                start = append_body(disp)
                rng = self._resolve_target(target, ordinal)
                if rng:
                    self.xrefs.append({
                        "source_kind": "block", "source_ref": block_idx,
                        "start": start, "end": start + len(disp),
                        "ts": rng[0], "te": rng[1],
                    })
                i = end_m + len(r"\ref*")
                continue

            if marker == "f" and not closing:
                end_m = run.find(r"\f*", i)
                if end_m == -1:
                    i = tok_end
                    continue
                body = run[tok_end:end_m]
                # Drop the caller flag ("+ ", "- ", "* ").
                cm = re.match(r"[+\-*?]\s?", body)
                if cm:
                    body = body[cm.end():]
                self._add_footnote(block_idx, block["len"], state["verse_key"],
                                   body, ordinal)
                i = end_m + len(r"\f*")
                continue

            # Unhandled inline marker (opening or closing): drop the token, keep
            # any text that follows.
            if not closing:
                self.warnings.append(f"{usfm}: dropped inline marker \\{marker}")
            i = tok_end

    # ---- footnotes ---------------------------------------------------------
    def _add_footnote(self, block_idx, offset, verse_key, body, ordinal):
        """Assemble a footnote body (fr/ft/fqa/fv + embedded \\ref) into display
        text, recording any embedded cross-references against this footnote."""
        fn_index = len(self.footnotes)
        parts = []
        plen = [0]
        label = [None]

        def emit(s):
            if not s:
                return 0
            # Skip leading whitespace so the popup body doesn't start with a space.
            if plen[0] == 0:
                s = s.lstrip()
                if not s:
                    return 0
            start = plen[0]
            parts.append(s)
            plen[0] += len(s)
            return start

        i, n = 0, len(body)
        while i < n:
            ch = body[i]
            if ch != "\\":
                j = body.find("\\", i)
                if j == -1:
                    j = n
                emit(body[i:j])
                i = j
                continue
            mm = re.match(r"\\(\+?[a-z0-9]+)(\*)?", body[i:])
            if not mm:
                emit("\\")
                i += 1
                continue
            marker, closing = mm.group(1), mm.group(2)
            tok_end = i + mm.end()
            if not closing and tok_end < n and body[tok_end] == " ":
                tok_end += 1

            if marker == "fr" and not closing:
                # The origin reference ("1:6"), running up to the next marker.
                fm = re.match(r"([^\\]*)", body[tok_end:])
                label[0] = fm.group(1).strip() or None
                i = tok_end + fm.end()
                continue
            if marker in ("ft", "fqa", "fk", "fl", "fw", "fp") :
                # A footnote text-run marker: emit nothing; following text flows.
                i = tok_end
                continue
            if marker == "fv":
                if closing:
                    i = tok_end
                    continue
                nm = re.match(r"(\d+)\\fv\*\s?", body[tok_end:])
                if nm:
                    emit(" " + nm.group(1) + " ")
                    i = tok_end + nm.end()
                    continue
                i = tok_end
                continue
            if marker == "ref" and not closing:
                end_m = body.find(r"\ref*", i)
                if end_m == -1:
                    i = tok_end
                    continue
                inner = body[tok_end:end_m]
                disp, _, target = inner.partition("|")
                disp = clean_ws(disp)
                start = emit(disp)
                rng = self._resolve_target(target, ordinal)
                if rng:
                    self.xrefs.append({
                        "source_kind": "note", "source_ref": fn_index,
                        "start": start, "end": start + len(disp),
                        "ts": rng[0], "te": rng[1],
                    })
                i = end_m + len(r"\ref*")
                continue
            # Unhandled footnote marker: drop token.
            i = tok_end

        text = clean_ws("".join(parts))
        self.footnotes.append({
            "block_idx": block_idx, "offset": offset, "verse_key": verse_key,
            "label": label[0], "text": text,
        })

    # ---- cross-reference target resolution ---------------------------------
    def _resolve_target(self, target, cur_ordinal):
        """Parse a USFM \\ref target ("JHN 1:1-5", "13:1-11", "1CH 15:29-16:3")
        into an inclusive (start_key, end_key), or None if unparseable."""
        target = target.strip()
        if not target:
            return None
        ordinal = cur_ordinal
        bm = re.match(r"([0-9][A-Z]{2}|[A-Z]{3})\s+", target)
        if bm:
            code = bm.group(1)
            if code not in ORDINAL:
                self.warnings.append(f"xref: unknown book code {code!r}")
                return None
            ordinal = ORDINAL[code]
            target = target[bm.end():]
        # C:V , C:V-V , C:V-C:V , or whole chapter C.
        m = re.match(r"(\d+):(\d+)(?:-(?:(\d+):)?(\d+))?$", target)
        if m:
            c1, v1 = int(m.group(1)), int(m.group(2))
            start = encode(ordinal, c1, v1)
            if m.group(4):
                c2 = int(m.group(3)) if m.group(3) else c1
                v2 = int(m.group(4))
                end = encode(ordinal, c2, v2)
            else:
                end = start
            return (start, end) if start <= end else (end, start)
        cm = re.match(r"(\d+)(?:-(\d+))?$", target)  # whole chapter(s)
        if cm:
            c1 = int(cm.group(1))
            c2 = int(cm.group(2)) if cm.group(2) else c1
            return (encode(ordinal, c1, 0), encode(ordinal, c2, MAX_VERSE))
        self.warnings.append(f"xref: unparseable target {target!r}")
        return None

    # ---- verse table -------------------------------------------------------
    def _ensure_verse(self, key, usfm, chapter, number):
        if key not in self.verses:
            self.verses[key] = {
                "usfm": usfm, "chapter": chapter, "verse": number, "parts": [],
            }
            self.verse_order.append(key)

    # ---- write -------------------------------------------------------------
    def write(self, path):
        if os.path.exists(path):
            os.remove(path)
        db = sqlite3.connect(path)
        try:
            db.executescript(SCHEMA_SQL)
            self._write_meta(db)
            self._write_books(db)
            self._write_verses(db)
            self._write_blocks(db)
            self._write_fts(db)
            db.commit()
            db.execute("VACUUM")
        finally:
            db.close()

    def _write_meta(self, db):
        meta = {
            "id": "bsb", "title": "Berean Standard Bible", "abbreviation": "BSB",
            "type": "bible", "language": "en", "versification": "english",
            "license": "Public Domain", "source_url": SOURCE_URL,
            "schema_version": str(SCHEMA_VERSION),
        }
        db.executemany("INSERT INTO metadata(key, value) VALUES (?, ?)",
                       list(meta.items()))

    def _write_books(self, db):
        max_ch = {}
        for key in self.verse_order:
            v = self.verses[key]
            c = max_ch.get(v["usfm"], 0)
            if v["chapter"] > c:
                max_ch[v["usfm"]] = v["chapter"]
        rows = []
        for usfm, ordinal, name, testament in CANON:
            if usfm in max_ch:
                rows.append((usfm, ordinal, name, testament, max_ch[usfm]))
        db.executemany(
            "INSERT INTO book(usfm, ordinal, name, testament, chapter_count) "
            "VALUES (?, ?, ?, ?, ?)", rows)

    def _write_verses(self, db):
        rows = []
        for key in self.verse_order:
            v = self.verses[key]
            # Fragments are (block_idx, text); join with a space where the block
            # changes (a paragraph break inside a verse), else contiguously.
            buf = []
            prev_block = None
            for block_idx, s in v["parts"]:
                if prev_block is not None and block_idx != prev_block:
                    buf.append(" ")
                buf.append(s)
                prev_block = block_idx
            text = _typo(clean_ws("".join(buf)))
            rows.append((key, v["usfm"], v["chapter"], v["verse"], text))
        db.executemany(
            "INSERT INTO verse(verse_key, usfm, chapter, verse, text) "
            "VALUES (?, ?, ?, ?, ?)", rows)

    def _write_blocks(self, db):
        # Assign final block ids (== list index + 1) and materialise content.
        block_rows = []
        for idx, b in enumerate(self.blocks):
            content = "".join(b["content"])
            block_rows.append((idx + 1, b["usfm"], b["chapter"], b["kind"],
                               b["start_key"], content))
        db.executemany(
            "INSERT INTO block(id, usfm, chapter, kind, start_key, content) "
            "VALUES (?, ?, ?, ?, ?, ?)", block_rows)

        db.executemany(
            "INSERT INTO verse_marker(block_id, start, end, verse_key, number) "
            "VALUES (?, ?, ?, ?, ?)",
            [(bi + 1, s, e, vk, num) for (bi, s, e, vk, num) in self.verse_markers])

        db.executemany(
            "INSERT INTO redletter(block_id, start, end) VALUES (?, ?, ?)",
            [(bi + 1, s, e) for (bi, s, e) in self.redletters])

        # Footnotes get ids (== index + 1); xrefs from notes reference that id.
        db.executemany(
            "INSERT INTO footnote(id, block_id, offset, verse_key, label, text) "
            "VALUES (?, ?, ?, ?, ?, ?)",
            [(i + 1, f["block_idx"] + 1, f["offset"], f["verse_key"],
              f["label"], f["text"]) for i, f in enumerate(self.footnotes)])

        xref_rows = []
        for x in self.xrefs:
            if x["source_kind"] == "block":
                source_id = x["source_ref"] + 1        # block id
            else:
                source_id = x["source_ref"] + 1        # footnote id
            xref_rows.append((x["source_kind"], source_id, x["start"], x["end"],
                              x["ts"], x["te"]))
        db.executemany(
            "INSERT INTO xref(source_kind, source_id, start, end, "
            "target_start_key, target_end_key) VALUES (?, ?, ?, ?, ?, ?)",
            xref_rows)

    def _write_fts(self, db):
        db.executescript("""
            INSERT INTO verse_fts(rowid, text) SELECT verse_key, text FROM verse;
            INSERT INTO verse_fts(verse_fts) VALUES ('optimize');
        """)


SCHEMA_SQL = """
PRAGMA journal_mode = OFF;
PRAGMA synchronous = OFF;

CREATE TABLE metadata (key TEXT PRIMARY KEY, value TEXT);

CREATE TABLE book (
  usfm          TEXT PRIMARY KEY,
  ordinal       INTEGER NOT NULL,
  name          TEXT NOT NULL,
  testament     TEXT NOT NULL,
  chapter_count INTEGER NOT NULL
);

CREATE TABLE verse (
  verse_key INTEGER PRIMARY KEY,
  usfm      TEXT NOT NULL,
  chapter   INTEGER NOT NULL,
  verse     INTEGER NOT NULL,
  text      TEXT NOT NULL
);

CREATE TABLE block (
  id        INTEGER PRIMARY KEY,
  usfm      TEXT NOT NULL,
  chapter   INTEGER NOT NULL,
  kind      TEXT NOT NULL,
  start_key INTEGER,
  content   TEXT NOT NULL DEFAULT ''
);
CREATE INDEX block_chapter ON block(usfm, chapter, id);

CREATE TABLE verse_marker (
  block_id  INTEGER NOT NULL,
  start     INTEGER NOT NULL,
  end       INTEGER NOT NULL,
  verse_key INTEGER NOT NULL,
  number    INTEGER NOT NULL
);
CREATE INDEX verse_marker_block ON verse_marker(block_id);

CREATE TABLE redletter (
  block_id INTEGER NOT NULL,
  start    INTEGER NOT NULL,
  end      INTEGER NOT NULL
);
CREATE INDEX redletter_block ON redletter(block_id);

CREATE TABLE footnote (
  id        INTEGER PRIMARY KEY,
  block_id  INTEGER NOT NULL,
  offset    INTEGER NOT NULL,
  verse_key INTEGER,
  label     TEXT,
  text      TEXT NOT NULL
);
CREATE INDEX footnote_block ON footnote(block_id);

CREATE TABLE xref (
  id               INTEGER PRIMARY KEY,
  source_kind      TEXT NOT NULL,        -- 'block' | 'note'
  source_id        INTEGER NOT NULL,
  start            INTEGER NOT NULL,
  end              INTEGER NOT NULL,
  target_start_key INTEGER NOT NULL,
  target_end_key   INTEGER NOT NULL
);
CREATE INDEX xref_source ON xref(source_kind, source_id);

CREATE VIRTUAL TABLE verse_fts USING fts5(
  text,
  content='verse',
  content_rowid='verse_key'
);
"""


def main():
    if not os.path.isdir(USFM_DIR):
        sys.exit(f"Missing USFM source dir: {USFM_DIR}")

    b = Builder()
    for usfm, ordinal, name, testament in CANON:
        path = os.path.join(USFM_DIR, f"{usfm}.usfm")
        if not os.path.exists(path):
            sys.exit(f"Missing book file: {path}")
        with open(path, encoding="utf-8") as fh:
            raw = fh.read()
        if raw and raw[0] == "﻿":
            raw = raw[1:]
        b.parse_book(usfm, raw)

    # Guard: character offsets are code-point indices; the Kotlin/Java consumer
    # uses UTF-16. They agree only if every char is in the BMP.
    astral = sum(1 for blk in b.blocks for s in blk["content"]
                 for c in s if ord(c) > 0xFFFF)
    if astral:
        b.warnings.append(f"{astral} astral (non-BMP) chars — offsets may desync on device")

    b.write(OUT_PATH)

    kb = round(os.path.getsize(OUT_PATH) / 1024)
    print(f"Parsed {len(b.verse_order)} verses, {len(b.blocks)} blocks, "
          f"{len(b.footnotes)} footnotes, {len(b.xrefs)} cross-references.")
    print(f"Wrote {OUT_PATH} ({kb}KB).")
    if b.warnings:
        from collections import Counter
        print(f"\n{len(b.warnings)} warning(s):")
        for msg, count in Counter(b.warnings).most_common(20):
            print(f"  [{count}x] {msg}")


if __name__ == "__main__":
    main()
